---
- hosts: all
  gather_facts: no
  become: yes
  become_user: root
  tasks:
    - name: Install packages needed for using ansible
      raw: test -e /usr/bin/python || (dnf install -y python2 python2-simplejson libselinux-python)
  tags:
    - prereq

- hosts: nodes
  become: yes
  become_user: root
  roles:
    - kubernetes-node
  tags:
    - prereq

- hosts: masters
  become: yes
  become_user: root
  roles:
    - kubernetes-master
  tags:
    - init
    - masters

- hosts: clients
  become: yes
  become_user: root
  roles:
    - kubernetes-client
  tags:
    - client

- hosts: workers
  become: yes
  become_user: root
  roles:
    - kubernetes-worker
  tags:
    - join
    - workers
