---
- hosts: nodes
  become: yes
  become_user: root
  tasks:

    - name: Upgrade kubelet
      dnf:
        name: kubelet-{{ kubernetes_version }}
        state: present

    - name: Restart kubelet service
      systemd:
        name: kubelet
        state: restarted

- hosts: clients
  become: yes
  become_user: root
  tasks:

    - name: Upgrade kubectl
      dnf:
        name: kubectl-{{ kubernetes_version }}
        state: present

- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Exclude kubernetes packages from upgrades
      include_role:
        name: kubernetes-node
        tasks_from: freeze-version.yml
