- name: Create kubeadm config
  template:
    src: ../templates/kubeadm-config.yaml.j2
    dest: /etc/kubernetes/kubeadm-config.yaml

- name: Initialize master
  command: kubeadm init --config /etc/kubernetes/kubeadm-config.yaml
  args:
    creates: /etc/kubernetes/admin.conf

- name: Store join command
  block:
    - command: kubeadm token create --print-join-command
      register: join_output
    - set_fact:
        join_command: "{{ join_output.stdout }}"

- import_tasks: "{{ network_provider }}.yml"
