- name: Create kubeadm config
  template:
    src: ../templates/kubeadm-config.yaml.j2
    dest: /etc/kubernetes/kubeadm-config.yaml

- name: Initialize master
  command: >
    kubeadm init --pod-network-cidr "10.244.0.0/16"
      --kubernetes-version {{ kubernetes_version }}
  when: kubernetes_version in ["1.9.3", "1.10.1"]

- name: Initialize master
  command: kubeadm init --config /etc/kubernetes/kubeadm-config.yaml
  args:
    creates: /etc/kubernetes/admin.conf
  when: kubernetes_version not in ["1.9.3", "1.10.1"]

- name: Store join command
  block:
    - command: kubeadm token create --print-join-command
      register: join_output
    - set_fact:
        join_command: "{{ join_output.stdout }}"

- include_tasks: "{{ network_provider }}.yml"
