- name: Create kubeadm config
  template:
    src: ../templates/kubeadm-config.yaml.j2
    dest: /etc/kubernetes/kubeadm-config.yaml

- name: Initialize master
  command: kubeadm init --config /etc/kubernetes/kubeadm-config.yaml
  args:
    creates: /etc/kubernetes/admin.conf

- name: Store join command
  block:
    - command: kubeadm token create --print-join-command
      register: join_output
    - set_fact:
        join_command: "{{ join_output.stdout }}"

- name: Install flannel network
  command: kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f "https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml?raw=true"
