- include_tasks: facts.yml

- name: Add hostname to /etc/hosts
  lineinfile:
    destfile: /etc/hosts
    state: present
    line: "{{ hostvars[item].ansible_host }} {{item}}"
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups['all'] }}"

- name: Remove swap from fstab
  lineinfile:
    destfile: /etc/fstab
    regexp: 'swap'
    state: absent
  register: swap

- name: Disable swap
  command: swapoff --all
  when: swap is changed

- name: Check if firewalld is installed
  stat:
    path: /usr/sbin/firewalld
  register: firewalld

- name: Disable firewall
  systemd:
    name: firewalld
    state: stopped
  when: firewalld.stat.exists

- include_tasks: "{{ container_runtime }}.yml"

- name: Set SELinux to permissive permanently
  lineinfile:
    destfile: /etc/sysconfig/selinux
    regexp: '^SELINUX='
    line: 'SELINUX=permissive'
    state: present
  register: selinux

- name: Disable SELinux
  command: setenforce 0
  when: selinux is changed

- include_tasks: "{{ kubernetes_flavor or 'vanilla' }}.yml"

- name: Start and enable kubelet service
  systemd:
    name: kubelet
    state: started
    enabled: yes

- name: Pass bridged IPv4 traffic to iptables
  block:
    - command: sysctl net.bridge.bridge-nf-call-iptables
      register: iptables
      changed_when: False
    - command: sysctl net.bridge.bridge-nf-call-iptables=1
      when: iptables.stdout != "net.bridge.bridge-nf-call-iptables = 1"
  when: network_provider in ["flannel", "kube-router"]

- name: Reload daemons
  systemd:
    daemon_reload: yes
