- name: Add hostname to /etc/hosts
  lineinfile:
    destfile: /etc/hosts
    state: present
    line: "{{ hostvars[item].ansible_host }} {{item}}"
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups['all'] }}"

- name: Remove swap from fstab
  lineinfile:
    destfile: /etc/fstab
    regexp: 'swap'
    state: absent
  register: swap

- name: Disable swap
  command: swapoff --all
  when: swap is changed

- name: Check if firewalld is installed
  stat:
    path: /usr/sbin/firewalld
  register: firewalld

- name: Disable firewall
  systemd:
    name: firewalld
    state: stopped
  when: firewalld.stat.exists

- name: Install docker
  dnf:
    name: docker
    # name: docker-2:1.13.1-51.git4032bd5.fc28

- name: Start and enable docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Set SELinux to permissive permanently
  lineinfile:
    destfile: /etc/sysconfig/selinux
    regexp: '^SELINUX='
    line: 'SELINUX=permissive'
    state: present
  register: selinux

- name: Disable SELinux
  command: setenforce 0
  when: selinux is changed

# -----------------------------------------------------------------------------
- name: Add kubernetes repo
  yum_repository:
    name: Kubernetes
    file: kubernetes
    description: Kubernetes repository
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-{{ ansible_architecture }}
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    gpgcheck: yes
    repo_gpgcheck: yes
  register: kubernetes_repo

- name: Refresh repo cache
  command: dnf clean metadata
  args:
    warn: no
  when: kubernetes_repo.changed

- name: Install parts
  dnf:
    name:
      # - kubelet
      # - kubeadm
      # - kubectl
      - kubelet-1.11.3
      - kubeadm-1.11.3
      - kubectl-1.11.3
      # Optional
      - iproute-tc

# -----------------------------------------------------------------------------

- name: Set image pull progress deadline
  lineinfile:
    destfile: /etc/sysconfig/kubelet
    regexp: '^KUBELET_EXTRA_ARGS='
    line: 'KUBELET_EXTRA_ARGS=--image-pull-progress-deadline=5m0s'
    state: present

- name: Start and enable kubelet service
  systemd:
    name: kubelet
    state: started
    enabled: yes

- name: Pass bridged IPv4 traffic to iptables
  command: sysctl net.bridge.bridge-nf-call-iptables
  register: iptables
  changed_when: False

- name: Pass bridged IPv4 traffic to iptables
  command: sysctl net.bridge.bridge-nf-call-iptables=1
  when: iptables.stdout != "net.bridge.bridge-nf-call-iptables = 1"

- name: Reload daemons
  systemd:
    daemon_reload: yes
